### ISSUE TITLE
When running socks5.py it complains about not able to find module "lib". 

### ISSUE THREAD

**Issue by dalel2000** [nneonneo/iOS-SOCKS-Server#28] opened 2024-08-27 15:13 UTC
Following the directions as described results in the main socks5.py not finding any lib.xxx entries.  I remove the leading lib. and it gets a little further, but I have to import all the files from the lib folder and then those files can't find stuff.

I don't see an easy fix that doesn't involve touching every file.  I also see no easy way to import the entire libraries.

Thoughts?

I am using pythonista 3.

**Comment by nneonneo** [comment] 2024-08-28 12:41
Sometimes this can be caused by iCloud not properly downloading all the files to your device. You can try moving the directory from the iCloud directory to your "This iPhone" directory and trying again. Sometimes, force-closing and restarting the app can also help.

**Comment by nneonneo** [comment] 2024-11-03 09:58
No activity for > 1 month, closing. Please feel free to reopen if the issue persists.

**Closed by nneonneo** 2024-11-03 09:58 UTC
